version: "3.9"

services:

docker-react-dev:
  container_name: docker-react-dev
  build:
    context: .
    dockerfile: Dockerfile-dev
  volume:
    - .:/app
    - '/app/node_modules'
  ports:
    - '3002:3000'
