version: "3.9"

services:
  docker-react-dev:
    container_name: docker-react-dev
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/app
      - "/app/node_modules"
    ports:
      - "3002:3000"

  docker-react-test:
    container_name: docker-react-test
    image: docker-react-cet_docker-react-dev #give an image instead of build
    volumes:
      - .:/app
      - "/app/node_modules"
        #Get rid of ports
    command: ["npm", "run", "test"] #Add specific command